ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'NO_DATA_FOUND';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'REVIEW_REQUIRED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'EXTRACTION_FAILED';
